### ISSUE TITLE
Proxy is not used

### ISSUE THREAD

**Issue by DarkShortie** [kodi-pvr/pvr.iptvsimple#349]
I'm using Kodi 18.6 on Android and I've configured Kodi to use a proxy to connect to the internet.
The IPTV Simple PVR addon seems to ignore this proxy and always tries to use a direct connection for streaming.

**Comment by phunkyfish** [comment]
Do you have an example channel entry where this happens?

I’ve never used the addon with a proxy so I don’t know what the expected behaviour should be.

Using kodi’s internal inputstream it should work but on an inputstream addon I’m not sure it would.

**Comment by DarkShortie** [comment]
I tried it with this channel list: http://kodi.my-cydia-ig.de/TV/tv_ch_wilmaa.m3u

How can I select if Kodi's internal inputstream or an inputstream addon is used?

**Comment by phunkyfish** [comment]
Try adding this before the the M3U entry in the M3U file. But I think this will only work in Kodi 19
```
#KODIPROP:inputstreamclass=inputstream.ffmpeg
```

I think in kodi 18 you need to set a mimetype so try this for m3u8:

```
#KODIPROP:mimetype=application/vnd.apple.mpegurl
```

**Comment by DarkShortie** [comment]
I made some tests. Without changing the m3u I see 2 requests for the m3u8 from the initial m3u and then a request to the selected audio m3u8. So 3 requests in total.

With 
`#KODIPROP:mimetype=application/vnd.apple.mpegurl`
it's the same.

With 
`#KODIPROP:inputstreamclass=inputstream.ffmpeg`
I see a request to the m3u8 using the proxy and then the 3 requests like described above without a proxy. So 4 requests in total.

**Comment by phunkyfish** [comment]
What platform is this on?

**Comment by DarkShortie** [comment]
Android

**Comment by phunkyfish** [comment]
So it appears the proxy is not being set in ffmpeg.

**Comment by phunkyfish** [comment]
Which fields have you set in the proxy config in kodi?

It’s not working in ffmpegdirect as the code is not there 😉

**Comment by phunkyfish** [comment]
Please post a debug log.

**Comment by phunkyfish** [comment]
Can you try the kodi nightly tomorrow with the latest 1.9.0 of ffmpegdirect?

You can now configure proxy settings in addon settings for ffmpegdirect. Let me know if it works.

**Comment by DarkShortie** [comment]
I wanted to try it with Kodi nightly, but the latest nightly releases are crashing on startup. The latest release which starts successfully is kodi-20200415-75732613-master-arm64-v8a.apk

I will try again in the next days.

**Comment by phunkyfish** [comment]
There was a new logging framework added to kodi. It may take a couple of days to fix any issues.

**Comment by phunkyfish** [comment]
Does your proxy have a username and password? You never stated what type of proxy you are using socks/http etc. or any other details.

A curl bug was just fixed in Kodi. So maybe try the latest kodi 18 build tomorrow and see does it make a difference.

**Comment by DarkShortie** [comment]
I tested now with the latest Kodi 19 nightly, it starts now again but the proxy still doesn't work.

The proxy is a http proxy provided by Squid and doesn't need a username/password.

I will test Kodi 18 later today or tomorrow.

**Comment by phunkyfish** [comment]
Can you install inputstream.ffmppegdirect and configure the proxy in the addon settings and try that? You will need the right kodi props.

**Comment by dagwieers** [comment]
Ok, not sure if this is related, but there is a known issue with the proxy settings in Kodi. If you enable them, it requires a reboot to activate them. If you don't reboot, Kodi will not set the environment variables when running add-ons or external binaries. After a reboot it will.

For python add-ons we fixed this by not relying on the environment variables, but instead parsing the proxy settings and applying them right away. IMO this is a bug in Kodi, there is no good reason why a reboot would be needed in this case.

**Comment by mavericklin** [comment]
facing the same issue with Leia 18.9... after checking proxy log, looks like at the beginning it will go through proxy for m3u8 link resolution. But later when the streaming comes it bypass the proxy settings.

**Comment by roughnecks** [comment]
hmm, 5 years? Got the same issue on Windows, both store and desktop apps.
