### ISSUE TITLE
"Start channel number" /wo function

### ISSUE THREAD

**Issue by palasinio** [kodi-pvr/pvr.iptvsimple#363]
@phunkyfish: Start channel number is not working:
![grafik](https://user-images.githubusercontent.com/31258581/79918501-cd89a980-842c-11ea-8580-d4b1eb6d6082.png)
Tried /w Kodi 18.1 to 19 nightly.

The channels always start /w "1" and using another PVR parallel is not possible though.
![grafik](https://user-images.githubusercontent.com/31258581/79918632-1c374380-842d-11ea-8281-f08d5eaa9adc.png)

**Comment by palasinio** [comment]
PS: M3U to test with: https://gist.githubusercontent.com/noestreich/d699a3725845cdcf353667201bca1c33/raw/iplaytv.m3u

**Comment by phunkyfish** [comment]
I think this only works if you just use IPTV Simple. Once you have more then one PVR it won’t work.

I would like to fix this in kodi but I would need to find the time to do it.

**Comment by ksooo** [comment]
To use two PVR add-ons, define different client priorities in Kodi PVR settings, and uncheck use backend channel numbers.

**Comment by phunkyfish** [comment]
@palasinio can you try this again in Kodi 19? There is an advanced option available when using multiple PVR addons now.

**Comment by palasinio** [comment]
@phunkyfish: I tried /w the Kodi version from today - but unfortunately the DVBViewer plugin crashes Kodi 19 at the moment (right after installing)...

**Comment by phunkyfish** [comment]
You mean the dvbviewer pvr addon?  Do you have a crash log?

**Comment by palasinio** [comment]
I‘ll try tomorrow. Is crash log = debug log?

**Comment by phunkyfish** [comment]
No, you would usually get a crash log and a debug log. Usually in the same folder though. 

What platform are you running on?

**Comment by phunkyfish** [comment]
I think I found the issue in DVB Viewer: https://github.com/kodi-pvr/pvr.dvbviewer/pull/92

**Comment by phunkyfish** [comment]
DVB Viewer PR released. v6.0.1 should work now. Happy testing.

**Comment by palasinio** [comment]
Hi, sorry, still not working. Kodi nightly from today, DVBViewer pvr plugin still not working  - no connect /w user,pw; crash /wo user/pw.

So I still can't test.


[kodi_stacktrace-19.0-ALPHA1 Git_20200626-e64b3034b5-20200627-234130.zip](https://github.com/kodi-pvr/pvr.iptvsimple/files/4841287/kodi_stacktrace-19.0-ALPHA1.Git_20200626-e64b3034b5-20200627-234130.zip)
[kodi_stacktrace-19.0-ALPHA1 Git_20200626-e64b3034b5-20200627-235251.zip](https://github.com/kodi-pvr/pvr.iptvsimple/files/4841298/kodi_stacktrace-19.0-ALPHA1.Git_20200626-e64b3034b5-20200627-235251.zip)

**Comment by phunkyfish** [comment]
Ah, I see another issue. Sorry I have no dvbviewer backed to check this on.

Can you check this build: https://jenkins.kodi.tv/job/kodi-pvr/job/pvr.dvbviewer/job/PR-96/1/artifact/cmake/addons/build/zips/pvr.dvbviewer+windows-x86_64/pvr.dvbviewer-6.0.2.zip

PR for fix is here: https://github.com/kodi-pvr/pvr.dvbviewer/pull/96

**Comment by palasinio** [comment]
Hi, I'm sorry :( 

the issue with te DVBViewer plugin should be fixed first - there seems to be something wrong with authentication.
But KODI shouldn't die cause of a plugin.

[Kodi.zip](https://github.com/kodi-pvr/pvr.iptvsimple/files/4853938/Kodi.zip)

**Comment by phunkyfish** [comment]
> Hi, I'm sorry :(
> 
> the issue with te DVBViewer plugin should be fixed first - there seems to be something wrong with authentication.
> But KODI shouldn't die cause of a plugin.
> 
> [Kodi.zip](https://github.com/kodi-pvr/pvr.iptvsimple/files/4853938/Kodi.zip)

Kodi can die with a binary addon failure. Python addons should not kill kodi.

We may need some help with this as I don’t have a backend to test with.

**Comment by palasinio** [comment]
If I can help, I'll try to.
The DVB plugin asks for version via http - this already needs authentication before.
If I disable user & pw in DVB web service and do a fresh install of Kodi and DVB plugin it will already die.

**Comment by palasinio** [comment]
There seems to be a version 6.0.4 of the dvbviewer pvr addon where something with username/pw is fixed.
Any idea, where to get a build from?

**Comment by palasinio** [comment]
Okay, sorry, found it somehow.
Still crashes (?).
[KODI crashlog.zip](https://github.com/kodi-pvr/pvr.iptvsimple/files/4940270/KODI.crashlog.zip)

**Comment by phunkyfish** [comment]
I think there is a 6.0.5 soon.

**Comment by phunkyfish** [comment]
Can you post here: https://github.com/manuelm/pvr.dvbviewer/issues/45

**Comment by palasinio** [comment]
@phunkyfish: THX for your patience. Both pvr plugins can now co exist (DVBViewer and yours).
Thank you very much!

**Comment by phunkyfish** [comment]
Is start channel number working for you now?

**Comment by palasinio** [comment]
Yes, it does, if I choose "use backend channel numbers":
![grafik](https://user-images.githubusercontent.com/31258581/88105241-e6c50200-cba3-11ea-95f1-95abebf654ed.png)

**Comment by phunkyfish** [comment]
Cool!
