### ISSUE TITLE
Compressed EPG

### ISSUE THREAD

**Issue by ghost** [kodi-pvr/pvr.iptvsimple#476]
Hello, does Simple IPTV client also support compressed XZ EPG data?
And if not, can you please add support for it?

**Comment by phunkyfish** [comment]
Is the format of the data inside the file XMLTV?

Why not just try it?

**Comment by ghost** [comment]
Hi, I tried indeed and yes, the data inside is XMLTV  format when extracting it using 7-zip.

Downloaded this one for test:
http://www.xmltvepg.nl/rytecNL_Basic.xz

**Comment by ghost** [comment]
Adding add-on "Archive support" doesn't help either.

**Comment by phunkyfish** [comment]
Adding support for another compression format is not an easy thing to do as this is a binary addon written in C++. I will try to see how easy/not easy this is at some point.

**Comment by ghost** [comment]
Thank you!

**Comment by phunkyfish** [comment]
Question. This data is usually used on Enigma2 devices. It’s not typically loaded via iptvsimple. What’s your use case?

**Comment by Evandro1975** [comment]
Not only Enigma, many Android App support the .xz compression version of EPG

**Comment by phunkyfish** [comment]
From the Rytec data source or others?

**Comment by Evandro1975** [comment]
In Italy we have epg-guide.com that provides EPG for italian TV in both format gz and xz but they recommend the xz because is more compressed and faster to download

**Comment by matthuisman** [comment]
If your still looking, a possible option is my IPTV Merge. That supports XZ in Kodi 19. You could use that to download and extract the epg and then pass it onto IPTV Simple Client

https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html

**Comment by phunkyfish** [comment]
I think I have this done natively on a branch somewhere. Just have to find it.

**Comment by ghost** [comment]
> If your still looking, a possible option is my IPTV Merge. That supports XZ in Kodi 19. You could use that to download and extract the epg and then pass it onto IPTV Simple Client
> 
> https://www.matthuisman.nz/2019/02/iptv-merge-kodi-add-on.html

O thanks, looks great indeed! I will give it a try! ;-)

**Comment by ghost** [comment]
> I think I have this done natively on a branch somewhere. Just have to find it.

That would be great as well!

**Comment by phunkyfish** [comment]
Ya, sorry, I had forgotten I never released it. Here is the PR: https://github.com/kodi-pvr/pvr.iptvsimple/pull/502

What platform do you run on for testing?

**Comment by ghost** [comment]
Great! I use Windows 10 for testing.

**Comment by phunkyfish** [comment]
Just a build issue on windows to fix. It’s probably why I left I never released it. Will ping back here once it’s ready.

**Comment by retrofan1979** [comment]
Okay, too bad. And what about AndroidTV platform?

**Comment by phunkyfish** [comment]
Testbuilds for windows: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-502/5/artifacts

**Comment by phunkyfish** [comment]
Testbuilds including Android: https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-502/8/pipeline

**Comment by ghost** [comment]
Thanks! BTW, does Simple IPTV client also support multiple EPG sources for a single playlist?

**Comment by phunkyfish** [comment]
Did you test that it works?

No, it does not support multiple EPG sources. If that's what you need then you want iptvmerge, webgrab++ etc.

**Comment by ghost** [comment]
I will try tomorrow ;-)

**Comment by phunkyfish** [comment]
Great, thanks!

**Comment by phunkyfish** [comment]
Logic error in previous testbuilds. Try these instead:

https://jenkins.kodi.tv/blue/organizations/jenkins/kodi-pvr%2Fpvr.iptvsimple/detail/PR-502/13/artifacts

**Comment by ghost** [comment]
Just tried the Windows 10 64-bits version and it works, however, only when the xz file is locally saved first, not when I'm pointing to the URL directly on internet.

**Comment by phunkyfish** [comment]
Do you have a log for when it is on the net?

Or able to share the URL you use on gitter.im?

**Comment by ghost** [comment]
> Hi, I tried indeed and yes, the data inside is XMLTV format when extracting it using 7-zip.
> 
> Downloaded this one for test:
> http://www.xmltvepg.nl/rytecNL_Basic.xz

**Comment by phunkyfish** [comment]
Great, thanks. Will let you know once I have new test builds.

**Comment by phunkyfish** [comment]
The URL you provided works for me @retrofan1979 when on the net.

Do you have more details on how it fails, possibly a debug log?

**Comment by phunkyfish** [comment]
Is it possible that the EPG is not loaded as the files are the same or that an EPG load is not required? That can be checked by just clearing the PVR data which would force a reload.

**Comment by ghost** [comment]
I already forced it, but the EPG only loads from downloaded file in your app, but not from URL directly when I test.

Never mind, thanks for trying. IPTV Merge works fine.

**Comment by phunkyfish** [comment]
> I already forced it, but the EPG only loads from downloaded file in your app, but not from URL directly when I test.
> 
> Never mind, thanks for trying. IPTV Merge works fine.

It’s not a useful feature if it doesn’t work for remote files. We should figure out why it doesn’t work remotely.

**Comment by ghost** [comment]
How can I provide a log file for you?

**Comment by phunkyfish** [comment]
You can use paste.kodi.tv or use a GitHub gist.

Best if you enable debug mode. Restart, and then submit the log after it starts up. https://kodi.wiki/view/Log_file/Easy

**Comment by ghost** [comment]
Does this also work with Kodi from Windows Store? KODI folder isn't created in Roaming folder. I also enabled option to see hidden files and folders. Ofcourse I enabled the debug mode.
I also activated the archive support app, but still no luck.

**Comment by phunkyfish** [comment]
On windows the log file will be here: %APPDATA%\Kodi\kodi.log (if you just put %APPDATA%\Kodi into the run bar is will open the folder for you).

You can open that in notepad, copy the contents and just manually paste it into paste.kodi.tv

Sorry, I don't use windows so I'm not sure if the log uploaded works there or not. But I assume it does.

**Comment by ghost** [comment]
Indeed, in Windows version it does create kodi.log, but it seems when using the KODI version from Windows Store, it doesn't. I thought I got crazy... ;-)

Anyway, here's the log: https://paste.kodi.tv/luqeyabuva.kodi

**Comment by phunkyfish** [comment]
:)

Ok. So in this log there is no attempt to load the EPG file. So it doesn't even try. I.e. kodi does not request for the addon to load it. 

A trick you can use to force loading the EPG on startup is to Enable catchup in the addon settings (just go the catchup tab in the add-on settings). All this really does is load a local cache of the EPG data in the addon but will allow you to test this more easily. Once you do that you will see log statements like these. Even if DEBUG mode is off.

```
INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadChannelEpgs - Loaded '1' EPG channels.
INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEpgEntries - Loaded '0' EPG entries.
INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadGenres - Loaded 2 genres
INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEPG - EPG Loaded - 3553 (ms)
```

**Comment by ghost** [comment]
Enabled catchup and this is the result:

2021-04-04 12:01:27.064 T:17188    INFO <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - iptvsimple::PlaylistLoader::LoadPlayList - Loaded 23 channels.
2021-04-04 12:01:27.065 T:17188   ERROR <general>: CCurlFile::FillBuffer - Failed: URL using bad/illegal format or missing URL(3)
2021-04-04 12:01:27.065 T:17188   ERROR <general>: CCurlFile::Open failed with code 0 for http://www.xmltvepg.nl/rytecNL_Basic.xz
:
                                                   
2021-04-04 12:01:27.065 T:17188   ERROR <general>: XFILE::CFileCache::Open - <http://www.xmltvepg.nl/rytecNL_Basic.xz
> failed to open
2021-04-04 12:01:27.065 T:17188   ERROR <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - iptvsimple::Epg::GetXMLTVFileWithRetries - Unable to load EPG file 'http://www.xmltvepg.nl/rytecNL_Basic.xz
':  file is missing or empty. :1th try.

**Comment by ghost** [comment]
How can the log be removed from paste.kodi.tv? Or can you do it?

**Comment by phunkyfish** [comment]
It get's removed after a month automatically. Can you post your settings.xml for iptvsimple. It will be in `userdata\addon_data\pvr.iptvsimple`

We're getting closer...

**Comment by ghost** [comment]
[settings.zip](https://github.com/kodi-pvr/pvr.iptvsimple/files/6254379/settings.zip)
Here it is.

I see some strange characters after the filename, is that okay?

<setting id="epgUrl">http://www.xmltvepg.nl/rytecNL_Basic.xz&#x0D;</setting>

**Comment by phunkyfish** [comment]
Nope, that is why it’s not working. It must have been added when you copy pasted the URL.

**Comment by phunkyfish** [comment]
You can either just edit the settings.xml to remove them or see can you remove them in the addon settings UI.

**Comment by phunkyfish** [comment]
That character sequence if the code for carriage return.

**Comment by ghost** [comment]
Probably this isn't that easy as it looks like. In settings UI those characters are not there.
When changing the settings.xml, nothing changes at all.
I already cleared the cache as well.

**Comment by phunkyfish** [comment]
> Probably this isn't that easy as it looks like. In settings UI those characters are not there.
> When changing the settings.xml, nothing changes at all.
> I already cleared the cache as well.

The file is only loaded on startup. Shut kodi down, fix the file, then startup up kodi and it should be fixed.

**Comment by ghost** [comment]
Sorry, still no luck. Maybe an issue with Windows version of KODI?
To be sure: tvg-id flag is also supported as well when using compressed xz XMLTV file as with uncompressed XMLTV file?

**Comment by phunkyfish** [comment]
> Sorry, still no luck. Maybe an issue with Windows version of KODI?

Unlikely

>To be sure: tvg-id flag is also supported as well when using compressed xz XMLTV file as with uncompressed XMLTV file?

Yes, the only thing that differs is the compression method. Everything else is the same.

Can you create and post a new debug log and supply the settings.xml since you fixed the issue? It is going to be something minor.

**Comment by ghost** [comment]
I hope it's something minor indeed.
Here's the new debug log:
https://paste.kodi.tv/xoqebagoya.kodi

**Comment by phunkyfish** [comment]
I think you may have disabled catchup for this log ;) There is no attempt to load the EPG data.

**Comment by phunkyfish** [comment]
> I think you may have disabled catchup for this log ;) There is no attempt to load the EPG data.

Please also post your current settings.xml

**Comment by ghost** [comment]
O, you're right ;-)

Here it is: https://paste.kodi.tv/zucewutiyu.kodi

**Comment by ghost** [comment]
[settings.zip](https://github.com/kodi-pvr/pvr.iptvsimple/files/6254710/settings.zip)

**Comment by phunkyfish** [comment]
It loaded the file correctly in your log!

**Comment by ghost** [comment]
That's nice, but I still don't see the EPG.

**Comment by phunkyfish** [comment]
Now that we know that the addon is loading a local cache you should clear all PVR data and it should appear.

It worked for me when I started with the URL with carriage return at the end and then removed it on the next start.

**Comment by retrofan1979** [comment]
I already did, but it doesn't.

**Comment by phunkyfish** [comment]
> I already did, but it doesn't.

Let me check what I did again.

**Comment by ghost** [comment]
Thanks, but anyway, it's a strange issue. Maybe a fix for KODI 19.1?

**Comment by phunkyfish** [comment]
There is no fault I can find. I added a new test channel which has the tvg-id of `ComedyCentralXtra.nl`. It works as you will see from the screenshot. All the other channels have ids that are not in the EPG file.

<img width="2099" alt="Screenshot 2021-04-04 at 16 31 39" src="https://user-images.githubusercontent.com/4601187/113513799-3e08d800-9563-11eb-99c0-9480e24331e6.png">

**Comment by phunkyfish** [comment]
Try one more thing. Go to `Kodi Settings->PVR and Live TV->Guide->Clear Data`.

See if that is any different.

The bug might be that clearing data from the `General` tab in Kodi PVR Settings does not clear EPG data.

**Comment by ghost** [comment]
Yes, I think that's the bug indeed. I now re-installed KODI from scratch and now it does work ;-) Thanks for your help!
